src/Admin/Entity/User.php
<?php

namespace App\Admin\Entity;

use App\Admin\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% set pageTitle = ((block('page_title') is defined) and (block('page_title') is not empty)) ? block('page_title') : '' %}
    {% set pageDesc = ((block('page_desc') is defined) and (block('page_desc') is not empty)) ? block('page_desc') : '' %}

    <title>
        Youth Pages | News For Youth
        {{ pageTitle ? '| ' ~ pageTitle : '' }}
        {{ pageDesc ? '| ' ~ pageDesc : '' }}
    </title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,400&display=swap" rel="stylesheet">
    <link href="{{ asset('assets/css/icons/icomoon/styles.css') }}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://storage.googleapis.com/non-spec-apps/mio-icons/latest/twotone.css">
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">

    <link href="{{ asset('assets/css/icons/fontawesome/styles.min.css') }}" rel="stylesheet" type="text/css"> 
    <link href="{{ asset('assets/css/bootstrap.css') }}" rel="stylesheet" type="text/css">
    {#<link href="{{ asset('assets/css/uikit.min.css') }}" rel="stylesheet" type="text/css">#}
    <link href="{{ asset('assets/css/core.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/css/components.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/css/colors.css') }}" rel="stylesheet" type="text/css">
    <!-- <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet" type="text/css"> -->
    <link href="{{ asset('assets/css/select2.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/css/nepaliDatePicker.css') }}" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->
    {# <!-- <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet" type="text/css"> --> #}
    <link href="{{ asset('assets/css/hms-style.css') }}" rel="stylesheet" type="text/css">
        {% block stylesheets %}

            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

         <!-- Core JS files -->
    <script type="text/javascript" src="{{ asset('assets/js/plugins/loaders/pace.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/core/libraries/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/core/libraries/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/loaders/blockui.min.js') }}"></script>
    <!-- /core JS files -->

    <!-- Theme JS files -->
    <script type="text/javascript" src="{{ asset('assets/js/plugins/ui/drilldown.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/visualization/d3/d3.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/visualization/d3/d3_tooltip.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/switchery.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/bootstrap_multiselect.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/ui/moment/moment.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/pickers/daterangepicker.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/pickers/datepicker.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript"
            src="{{ asset('assets/js/plugins/pickers/nepali-date-picker/jquery.nepaliDatePicker.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/core/app.js') }}"></script>
{#    <script type="text/javascript" src="{{ asset('assets/js/core/custom-script.js') }}"></script>#}

    <script src="{{ asset('assets/js/bootstrap-datepicker.js') }}"></script>
    <script src="{{ asset('assets/js/uikit.min.js') }}"></script>
    <script src="{{asset('assets/js/bootstrap-tagsinput.js')}}"></script>
    <script src="{{asset('assets/js/sweetalert.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/js/layout_navbar_secondary_fixed.js')}}"></script>
    <!-- /theme JS files -->
     <script src="{{ asset('assets/js/plugins/media/fancybox.min.js') }}"></script>
    <script src="{{ asset('assets/js/pages/gallery.js') }}"></script>
    <script src="{{ asset('assets/js/select2.min.js') }}"></script>
    <script src="{{ asset('assets/js/notify.js') }}"></script>

    <script src="{{ asset('assets/js/plugins/editors/ckeditor/v5/classic/ckeditor.js') }}"></script>
</head>
    <body>
            {% include 'navbar.html.twig' %}
            {% include 'menubar.html.twig' %}

            <!-- Page container -->
<div class="page-container">

    <!-- Page content -->
    <div class="page-content">

        {# {% include 'Admin/Templates/Includes/sidebar.html.twig' %} #}


        <!-- Main content -->
        <div class="content-wrapper">

            {% block breadcumb_bar %}
                <div class="page-header page-header-default">
                    <div class="breadcrumb-line">
                        <div class="container-fluid">

{#                            {{ asprega_breadcrumb('Admin/Templates/Includes/breadcrumb.html.twig') }}#}
                            {#{{ apy_breadcrumb_trail_render('Admin/Templates/Includes/breadcrumb.html.twig') }}#}

                            {#<ol class="breadcrumb">#}
                                {#<li>#}
                                    {#<a href="{{ path('fn_main_dashboard') }}">#}
                                        {#<i class="icon-home2 position-left"></i>#}
                                        {#Dashboard#}
                                    {#</a>#}
                                {#</li>#}
                            {#</ol>#}

                            <ul class="breadcrumb-elements">
                                {% block action %}{% endblock %}
                            </ul>

                        </div>
                    </div>
                </div>
            {% endblock %}

            <!-- Content area -->
            <div class="content">

                {% if is_granted('ROLE_PREVIOUS_ADMIN') %}
                    <div class="row">
                        <div class="col-md-12 margin-b-10">
                            <div class="alert disabled alert-warning">
                                <i class="fa fa-exclamation-triangle"></i> &nbsp;
                                Currently logged in as {{ app.user.username }}.
                                <a href="{{ path('fn_main_dashboard', {'_switch_user': '_exit'}) }}">Switch Back</a>
                            </div>
                        </div>
                    </div>
                {% endif %}
                {% if (app.session.flashbag.peekAll|length > 0) or (errorMessage is defined) %}
                    <div class="row">
                        <div class="col-md-12 margin-b-10">
                            {% if app.session.flashbag.peekAll|length > 0 %}
                                {% for type, messages in app.session.flashbag.all %}
                                    {% for message in messages %}
                                        {% if type == 'success' %}
                                            {% set alertClass = 'alert-success' %}
                                            {% set faClass = 'fa-check-circle' %}
                                        {% elseif type == 'warning' %}
                                            {% set alertClass = 'alert-warning' %}
                                            {% set faClass = 'fa-exclamation-triangle' %}
                                        {% else %}
                                            {% set alertClass = 'alert-danger' %}
                                            {% set faClass = 'fa-exclamation-triangle' %}
                                        {% endif %}

                                        <div class="alert disabled {{ alertClass }}">
                                            <i class="fa {{ faClass }}"></i> &nbsp;
                                            {{ message|trans({}, domain|default('messages')) }}
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                            {% endif %}
                            {% if errorMessage is defined %}
                                <div class="alert disabled alert-danger">
                                    <i class="fa fa-exclamation-triangle"></i> &nbsp;
                                    {{ errorMessage }}
                                </div>
                            {% endif %}
                        </div>
                        <div class="clearfix"></div>
                    </div>
                {% endif %}

                {% block content %}{% endblock %}


                <!-- Footer -->
                <div class="footer hrm-footer">
                    &copy; {{ 'now'|date('Y') }}. <a href="//electronsolution.com.np" target="_blank">Electron Solution Pvt. Ltd.</a>
                </div>
                <!-- /footer -->

            </div>
            <!-- /content area -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</div>
<!-- /page container -->


    </body>

    
        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
</html>

templates/menubar.html.twig
<div class="navbar navbar-default affix-top hms-navbar-secondary" id="navbar-second">
    <div class="container-fluid">
        <ul class="nav navbar-nav no-border visible-xs-block">
            <li><a tabindex="-1" class="text-center collapsed" data-toggle="collapse" data-target="#navbar-second-toggle"><i class="icon-menu7"></i></a></li>
        </ul>
        <div class="navbar-collapse collapse " id="navbar-second-toggle">
            <ul class="nav navbar-nav">
                {# Staff #}
                    <li class="dropdown mega-menu mega-menu-wide ">
                        <a tabindex="-1" href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user-tie position-left"></i> News <span class="caret"></span></a>
                        <div class="dropdown-menu dropdown-content">
                            <div class="dropdown-content-body">
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="dd-wrapper">
                                            <span class="menu-heading underlined">News</span>
                                            <ul class="menu-list has-children dd-menu">
                                            {{ fn_sidebar_link('', path('app_news_create'), 'News Create', {'icon':'icon-three-bars'}) }}
                                            {{ fn_sidebar_link('', path('app_news_list'), 'News List', {'icon':'icon-three-bars'}) }}
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <span class="menu-heading underlined">News List</span>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="dd-wrapper">
                                                    <ul class="menu-list has-children dd-menu">
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                        <div class="col-md-3">
                                            <span class="menu-heading underlined">News Setup</span>
                                            <div class="row">
                                                <div class="dd-wrapper">
                                                    <ul class="menu-list has-children dd-menu">
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                </div>
                            </div>
                        </div>
                    </li>
                {# Staff End---- #}


                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-plus-square position-left"></i> Inventory <span class="caret"></span>
                        </a>

                                <ul class="dropdown-menu width-250">
                               </ul>
                    </li>

                {# Acc #}
                <li class="dropdown mega-menu mega-menu-wide ">
                    <a tabindex="-1" href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-calculator2 position-left"></i> Videos <span class="caret"></span></a>

                    <div class="dropdown-menu dropdown-content">
                        <div class="dropdown-content-body">
                            <div class="row">
                                    <div class="col-md-3">
                                            <span class="menu-heading underlined">Vendor</span>
                                            <ul class="menu-list">
                                            </ul>

                                            <span class="menu-heading underlined">Expense</span>
                                            <ul class="menu-list">
                                            </ul>

                                            <span class="menu-heading underlined">Fixed Asset</span>
                                            <ul class="menu-list">
                                            </ul>
                                    </div>

                                    <div class="col-md-3">
                                    <span class="menu-heading underlined">Account</span>
                                    <ul class="menu-list has-children dd-menu"></ul>
                                    </div>

                                    <div class="col-md-3">
                                    <span class="menu-heading underlined">Payment/Receipt Accounts</span>
                                    <ul class="menu-list has-children dd-menu">
                                    </ul>
                                    </div>
                        
                            </div>
                        </div>
                    </div>
                </li>

            </ul>


        </div>
    </div>
</div>

templates/navbar.html.twig
<!-- Main navbar -->
<div class="navbar navbar-inverse hms-navbar">
    <div class="navbar-header">
        <a tabindex="-1" class="navbar-brand" href="{{ path('app_news_create') }}" >
            <img src="{{ asset('assets/images/full_logo.png') }}" alt="">
        </a>

        <ul class="nav navbar-nav visible-xs-block">
            <li><a tabindex="-1" data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
            <li><a tabindex="-1" class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>
    </div>

    <div class="navbar-collapse collapse" id="navbar-mobile">
        <ul class="nav navbar-nav">
            {# <li><a tabindex="-1" class="sidebar-control sidebar-main-toggle hidden-xs"><span role="img" aria-label="menu-fold" class="fn-ico fncon-menu-fold nav-icon"><svg viewBox="64 64 896 896" focusable="false" class="" data-icon="menu-fold" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M408 442h480c4.4 0 8-3.6 8-8v-56c0-4.4-3.6-8-8-8H408c-4.4 0-8 3.6-8 8v56c0 4.4 3.6 8 8 8zm-8 204c0 4.4 3.6 8 8 8h480c4.4 0 8-3.6 8-8v-56c0-4.4-3.6-8-8-8H408c-4.4 0-8 3.6-8 8v56zm504-486H120c-4.4 0-8 3.6-8 8v56c0 4.4 3.6 8 8 8h784c4.4 0 8-3.6 8-8v-56c0-4.4-3.6-8-8-8zm0 632H120c-4.4 0-8 3.6-8 8v56c0 4.4 3.6 8 8 8h784c4.4 0 8-3.6 8-8v-56c0-4.4-3.6-8-8-8zM115.4 518.9L271.7 642c5.8 4.6 14.4.5 14.4-6.9V388.9c0-7.4-8.5-11.5-14.4-6.9L115.4 505.1a8.74 8.74 0 000 13.8z"></path></svg></span></a></li>
            <li> #}
            <form action="#">
                <div class="form-group-feedback form-group-cms-search">
                    <input tabindex="-1" type="search" class="form-control" placeholder="Search" autocomplete="off">
                    <div class="form-control-feedback">
                        <i class="icon-search4 font-size-base"></i>
                    </div>
                </div>
            </form>
            </li>

        </ul>
        {# <ul class="nav navbar-nav content-header__menu">
                 <li><a href="" data-popup="tooltip" data-placement="bottom" class="" title="" data-original-title="Write preception"><i class=" icon-file-plus position-left"></i> Write a preception </a>
               </li>
                <li><a href="" data-popup="tooltip" data-placement="bottom" class="" title="" data-original-title="Generate Report"><i class=" icon-file-text2 position-left"></i> Generate Report </a>
               </li>
           </ul> #}
        <ul class="nav navbar-nav navbar-right fn-top-nav-right">
            {#            {{ fn_tiny_button('', 'fn_bed_status', 'Bed Status', {'icon':'icon-bed2', 'data-placement':'bottom'}) }}#}
            <li><a tabindex="-1" href="{{ path('app_news_create')}}" data-popup="tooltip" data-placement="bottom" class="" title="" data-original-title="New Bill"><i class="icon-file-spreadsheet "></i>  </a>
            </li>
            <li><a tabindex="-1" href="{{ path('app_news_create')}}" data-popup="tooltip" data-placement="bottom" class="" title="" data-original-title="Create Appointment"><i class=" icon-pencil5 "></i>  </a>
            </li>
            <li>
            </li>




            <li class="dropdown dropdown-user">
                <a tabindex="-1" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="{{ asset('assets/images/default.png') }}" alt="">
                    {# <span>{{ app.user.username }}</span> #}
                    <i class="caret"></i>
                </a>

                <ul class="dropdown-menu dropdown-menu-right">
                    {% if  is_granted('ROLE_SUPER_ADMIN') != 1 %}
{#                        <li><a href="{{ path('fn_site_employee_update',{'id':app.user.employee.id}) }}"><i class="icon-user-plus"></i> My profile</a></li>#}
                    {% endif %}
{#                    <li><a href="{{ path('fn_site_change_password') }}"><i class="fa fa-key"></i> Change Password</a></li>#}

                </ul>
            </li>
        </ul>
    </div>
</div>
<!-- /main navbar -->

templates/reg-base.html.twig
<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% set pageTitle = ((block('page_title') is defined) and (block('page_title') is not empty)) ? block('page_title') : '' %}
    {% set pageDesc = ((block('page_desc') is defined) and (block('page_desc') is not empty)) ? block('page_desc') : '' %}

    <title>
        Youth Pages | News For Youth
        {{ pageTitle ? '| ' ~ pageTitle : '' }}
        {{ pageDesc ? '| ' ~ pageDesc : '' }}
    </title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,400&display=swap" rel="stylesheet">
    <link href="{{ asset('assets/css/icons/icomoon/styles.css') }}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://storage.googleapis.com/non-spec-apps/mio-icons/latest/twotone.css">
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">

    <link href="{{ asset('assets/css/icons/fontawesome/styles.min.css') }}" rel="stylesheet" type="text/css"> 
    <link href="{{ asset('assets/css/bootstrap.css') }}" rel="stylesheet" type="text/css">
    {#<link href="{{ asset('assets/css/uikit.min.css') }}" rel="stylesheet" type="text/css">#}
    <link href="{{ asset('assets/css/core.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/css/components.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/css/colors.css') }}" rel="stylesheet" type="text/css">
    <!-- <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet" type="text/css"> -->
    <link href="{{ asset('assets/css/select2.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/css/nepaliDatePicker.css') }}" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->
    {# <!-- <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet" type="text/css"> --> #}
    <link href="{{ asset('assets/css/hms-style.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/css/login.css') }}" rel="stylesheet" type="text/css">
        {% block stylesheets %}

            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}
        </head>
<body>
{% block body %}

{% endblock %}
</body>
</html>